### ISSUE TITLE
criteria expression for DateTime is wrong

### ISSUE THREAD

**Issue by benchengnz** [vivet/DynamicExpression#14]
Hi there,
I have trouble for creating criteria expression for DateTime type.

The expression created is like this.
{x => (((x.OrganisationId != null) AndAlso (x.OrganisationId == 1)) AndAlso ((x.ContributionDate != null) AndAlso ((x.ContributionDate >= 1/11/2018 2:15:01 PM) AndAlso (x.ContributionDate <= 10/07/2019 2:15:01 PM))))}

it give me error like this.
System.Data.SqlClient.SqlException (0x80131904): Conversion failed when converting date and/or time from character string.\r\n   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n ...

my function

        public static Expression<Func<T, bool>> FilterExpression<T>(int OrgId, DateTime from, DateTime to, int ContributorId, string sortBy)
            where T : ContributionLine
        {
            CriteriaExpression criteraExpression;
            var builder = new CriteriaBuilder();
            var criteria = new List<CriteriaExpression>();
            criteraExpression = new CriteriaExpression();
            criteraExpression.Equal<int>("OrganisationId", OrgId);

            criteraExpression.Between<DateTime>("ContributionDate", from, to);

            if (ContributorId > 0)
            {
                criteraExpression.Equal<int>("ContributorId", ContributorId);
            }
            criteria.Add(criteraExpression);

            var  expression = builder.Build<T>(criteria);
            return expression ;
        } 
}

public void ContributionSummary(int OrgId,  DateTime from, DateTime to, int ContributorId, string sortBy )
        {

            var expression = ContributionService.FilterExpression<ContributionLine>(OrgId, from, to, ContributorId, sortBy);
            var summary = _context.ContributionLine.Where( expression )
               .ToList();
            Debug.WriteLine(summary.Count());
        }
}

Thank you very much.

**Comment by vivet** [comment]
Hi
Sorry didn't see the issue before now.
Will look at it one if the next days.

**Comment by benchengnz** [comment]
> Hi
> Sorry didn't see the issue before now.
> Will look at it one if the next days.

thank you so much. hopefully it's something I did wrong, just want some guidance. :)

**Comment by vivet** [comment]
Hi
I took a quick look.
First, I personally use the DateTime myself, allover the current projects I work on, and I experience the same issue. Second, the linq looks correct, so i think its related to SQL server, which could be related to the format of the datetime.  Conclusion, seems to me to be a problem with that.

**Comment by benchengnz** [comment]
vivet
you don't think the date string should have quotes around them
`{x => (((x.OrganisationId != null) AndAlso (x.OrganisationId == 1)) AndAlso ((x.ContributionDate != null) AndAlso ((x.ContributionDate >= 1/11/2018 2:15:01 PM) AndAlso (x.ContributionDate <= 10/07/2019 2:15:01 PM))))}`

should it be like this
`{x => (((x.OrganisationId != null) AndAlso (x.OrganisationId == 1)) AndAlso ((x.ContributionDate != null) AndAlso ((x.ContributionDate >= **'1/11/2018 2:15:01 PM')** AndAlso (x.ContributionDate <= '10/07/2019 2:15:01 PM'))))}`

also the date string is in my locale format which is dd/MM/yyyy should that be in like 'yyyy-MM-dd' format?

**Comment by vivet** [comment]
Hi
No quotes are not for DateTime in Linq, it's SQL.
I did a test using DateTime, by creating a list of objects with a DateTime property, and building and executing an expression, which provided me with the correct result. 
Seems the issue is related to the SQL conversion you do. The Linq is fine.

**Comment by vivet** [comment]
Did you figure out why the linq to sql failed?

**Comment by benchengnz** [comment]
no. i haven't.. might take a look later.

**Comment by benchengnz** [comment]
vivet, 
after I upgrade from my .net version from 2.1 to 2.2 the problem has gone away.
I will close this issue.
Thanks

**Comment by vivet** [comment]
Ok good.
