### ISSUE TITLE
Support for Array Property Type

### ISSUE THREAD

**Issue by justinushermawan** [vivet/DynamicExpression#16]
Hi, does it support for Array members type? For example:

`myCollection.Where(x => x.Values[0] == "someValue" && x.Values[1] == 12);`

**Comment by vivet** [comment]
Yes, that is if I understood correctly.
To query collections, use "myCollection[myProperty]".
You can't use indexers, cause I wouldn't know how many items is in the collection.

Hope it makes sense.

**Comment by vivet** [comment]
Did you manage to get it to work?

**Comment by justinushermawan** [comment]
Hi, no, I didn't. I use `System.Linq.Dynamic.Core` to get it to work and use it like this: `myCollection.AsQueryable().Where("Values[0].Equals(\"someString\") && Values[1].Equals(\"someString\")").ToList();`.

**Comment by vivet** [comment]
I am not sure how you are using it like that. As mentioned the library doesn't support indexers, and for good reason.
Maybe if you can add the complete snippet I can assist.
