### ISSUE TITLE
Order function

### ISSUE THREAD

**Issue by MyJimmyZhou** [vivet/DynamicExpression#17]
Maybe, you can change the function as following:

`
        public static IQueryable<T> Order<T>(this IQueryable<T> source, IOrdering ordering)
            where T : class
        {
            if (source == null)
                throw new ArgumentNullException(nameof(source));

            if (ordering == null)
                throw new ArgumentNullException(nameof(ordering));

            var parameter = Expression.Parameter(typeof(T));
            var property = Expression.Property(parameter, ordering.By);
            var expression = Expression.Lambda<Func<T, dynamic>>(Expression.Convert(property, typeof(object)), parameter);
            return ordering.Direction == OrderingDirection.Asc ? source.OrderBy(expression) : source.OrderByDescending(expression);
        }
`
It will be error when use type of Nullable Enum

**Comment by vivet** [comment]
Try make the change and i will evaluate it

**Comment by MyJimmyZhou** [comment]
> Try make the change and i will evaluate it

![image](https://user-images.githubusercontent.com/13486578/161931267-511d9913-2018-4e5d-9ec8-554c32a80dc3.png)
It's looks like I wasn't able to create a pull request

**Comment by vivet** [comment]
You will need to make a fork

**Comment by MyJimmyZhou** [comment]
> You will need to make a fork

I get it

**Comment by vivet** [comment]
I have merged the PR, and I also added some tests.
A new Nuget is published
