### ISSUE TITLE
can support like  Nullable<long> array

### ISSUE THREAD

**Issue by bingtianyiyan** [vivet/DynamicExpression#19]
can support this
 var criteriaExpression = new CriteriaExpression();
 criteriaExpression.In("IdList", new long?[] { 1, 2 });

**Comment by vivet** [comment]
Will take a look

**Comment by bingtianyiyan** [comment]
> Will take a look

ok, thanks for you .
Looking forward to the results of your modifications

**Comment by vivet** [comment]
You would need to do this
```
var criteriaExpression = new CriteriaExpression();
criteriaExpression.In("IdList[myProperty]", new long?[] { 1, 2 });
```
Then it will check if MyProperty is matching one of the values in the second parameter list.
Though this isn't currently supported but I will implement support for it

**Comment by bingtianyiyan** [comment]
thanks,Looking forward to~~~
