### ISSUE TITLE
In/Contains operators fail

### ISSUE THREAD

**Issue by valleen** [vivet/DynamicExpression#5]
Hey,

Thanks for the work.
I'm having trouble using In or Contains operator, here is my code:

`

        [TestMethod]
        public void GetExpressionWhenInTest()
        {
            var criteriaExpression = new CriteriaExpression();
            criteriaExpression.Contains("Name", new string[] { "Paul", "John"});

            var builder = new CriteriaBuilder();
            var expression = builder.GetExpression<TestType>(criteriaExpression);

            Assert.IsNotNull(expression);
            Assert.AreEqual("((x.Name != null) AndAlso x.Name.Trim().ToLower().EndsWith(\"value\".Trim().ToLower()))", expression.Body.ToString());
        }

`

**Comment by vivet** [comment]
Hi
Sorry i have completely missed your issue.
I have made several updates since, try with latest version.
Although I might have removed passing collections, cause as you say it was buggy.
I can re-add if needed.

**Comment by vivet** [comment]
Its solved.
Will close the issue.
